version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data-dev/redis:/data"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data-dev/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: masacarri
      POSTGRES_PASSWORD: masacarri
      POSTGRES_DB: masacarri_data
